language: ruby
rvm:
  - 2.5
  - 2.6
  - 2.7

gemfile:
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_5.0.gemfile
  - gemfiles/activerecord_5.1.gemfile
  - gemfiles/activerecord_5.2.gemfile
  - gemfiles/activerecord_6.0.gemfile
  - gemfiles/activerecord_6.1.gemfile

before_script:
  - "bundle exec rake db:setup PGUSER=postgres"

services:
  - postgresql
